[[constraint]]
  branch = "master"
  name = "github.com/FernandoCagale/serverless-infra"

[[constraint]]
  branch = "master"
  name = "github.com/awslabs/aws-lambda-go-api-proxy"

[[constraint]]
  name = "github.com/go-ozzo/ozzo-validation"
  version = "3.4.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.1"

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/auth0/go-jwt-middleware"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
